// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokSayim.Infrastructure.Data;

#nullable disable

namespace StokSayim.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402150711_mig5")]
    partial class mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolgeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BolgeKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SayimPlaniId", "BolgeKodu")
                        .IsUnique();

                    b.ToTable("Bolgeler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Ekip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("EkipAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EkipKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EkipKodu")
                        .IsUnique();

                    b.ToTable("Ekipler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<string>("EkipGrubuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId")
                        .IsUnique();

                    b.HasIndex("SayimPlaniId");

                    b.ToTable("EkipGruplari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipGrubuEkip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EkipGrubuId")
                        .HasColumnType("int");

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.Property<int>("EkipRolu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkipGrubuId");

                    b.HasIndex("EkipId");

                    b.ToTable("EkipGrubuEkipler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EkipKullanicilari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolEkip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.Property<int>("ErpKontrolOturumuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.HasIndex("ErpKontrolOturumuId");

                    b.ToTable("ErpKontrolEkipler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolMalzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErpKontrolEkipId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SayilanMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ErpKontrolEkipId");

                    b.ToTable("ErpKontrolMalzemeler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolOturumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SayimPlaniId");

                    b.ToTable("ErpKontrolOturumlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportDosyaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SayimPlaniId", "MalzemeKodu", "DepoKodu", "LotNo");

                    b.ToTable("ErpStoklar");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.GorevBildirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BildirimTipi")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsleyenKullaniciId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimOturumuId")
                        .HasColumnType("int");

                    b.Property<int?>("SayimTuruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsleyenKullaniciId");

                    b.HasIndex("SayimOturumuId");

                    b.HasIndex("SayimTuruId");

                    b.ToTable("GorevBildirimleri");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Malzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("GuncellemeKaynagi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OlcuBirimi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeKodu")
                        .IsUnique();

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ManuelKarar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KararTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KararVerenKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("KararVerilenDeger")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimTuruId")
                        .HasColumnType("int");

                    b.Property<int>("TurSonucuDetayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KararVerenKullaniciId");

                    b.HasIndex("SayimTuruId");

                    b.HasIndex("TurSonucuDetayId")
                        .IsUnique();

                    b.ToTable("ManuelKararlar");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.Property<int>("EkipRolu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimTuruId")
                        .HasColumnType("int");

                    b.Property<string>("SayimYapanKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.HasIndex("SayimTuruId");

                    b.HasIndex("SayimYapanKullaniciId");

                    b.ToTable("SayimKayitlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimKaydiDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SayilanMiktar")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SayimKaydiId")
                        .HasColumnType("int");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SayimKaydiId");

                    b.ToTable("SayimKaydiDetaylari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimOturumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AktifTurNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.Property<string>("SorumluKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId")
                        .IsUnique();

                    b.HasIndex("SayimPlaniId");

                    b.ToTable("SayimOturumlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimPlanDepoKodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepoAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimPlaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SayimPlaniId");

                    b.ToTable("SayimPlanDepoKodlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AktifEdenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AktifEdilemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SayimPlanlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcilamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KapanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimOturumuId")
                        .HasColumnType("int");

                    b.Property<int>("TurNo")
                        .HasColumnType("int");

                    b.Property<int>("TurTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SayimOturumuId");

                    b.ToTable("SayimTurlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimTuruKatilimci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.Property<int>("EkipRolu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SayimKaydiId")
                        .HasColumnType("int");

                    b.Property<int>("SayimTuruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.HasIndex("SayimKaydiId");

                    b.HasIndex("SayimTuruId");

                    b.ToTable("SayimTuruKatilimcilari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EslesilenSayisi")
                        .HasColumnType("int");

                    b.Property<int>("FarkliSayisi")
                        .HasColumnType("int");

                    b.Property<int>("GenelDurum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HesaplamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SayimTuruId")
                        .HasColumnType("int");

                    b.Property<int>("ToplamMalzemeSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SayimTuruId")
                        .IsUnique();

                    b.ToTable("TurSonuclari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucuDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Deger1")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Deger2")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Deger3")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<decimal?>("Fark")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FarkYuzdesi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KararTipi")
                        .HasColumnType("int");

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OnaylananDeger")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurSonucuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurSonucuId");

                    b.ToTable("TurSonucuDetaylari");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Bolge", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany("Bolgeler")
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipGrubu", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Bolge", "Bolge")
                        .WithOne("EkipGrubu")
                        .HasForeignKey("StokSayim.Domain.Entities.EkipGrubu", "BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany()
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipGrubuEkip", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.EkipGrubu", "EkipGrubu")
                        .WithMany("Ekipler")
                        .HasForeignKey("EkipGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.Ekip", "Ekip")
                        .WithMany("EkipGrubuEkipler")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("EkipGrubu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipKullanici", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Ekip", "Ekip")
                        .WithMany("EkipKullanicilari")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", "Kullanici")
                        .WithMany("EkipKullanicilari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolEkip", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Ekip", "Ekip")
                        .WithMany()
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.ErpKontrolOturumu", "ErpKontrolOturumu")
                        .WithMany("Ekipler")
                        .HasForeignKey("ErpKontrolOturumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("ErpKontrolOturumu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolMalzeme", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ErpKontrolEkip", "ErpKontrolEkip")
                        .WithMany("Malzemeler")
                        .HasForeignKey("ErpKontrolEkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErpKontrolEkip");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolOturumu", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany()
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpStok", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany("ErpStoklar")
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.GorevBildirimi", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", "IsleyenKullanici")
                        .WithMany()
                        .HasForeignKey("IsleyenKullaniciId");

                    b.HasOne("StokSayim.Domain.Entities.SayimOturumu", "SayimOturumu")
                        .WithMany("GorevBildirimleri")
                        .HasForeignKey("SayimOturumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimTuru", "SayimTuru")
                        .WithMany()
                        .HasForeignKey("SayimTuruId");

                    b.Navigation("IsleyenKullanici");

                    b.Navigation("SayimOturumu");

                    b.Navigation("SayimTuru");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ManuelKarar", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", "KararVerenKullanici")
                        .WithMany()
                        .HasForeignKey("KararVerenKullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimTuru", "SayimTuru")
                        .WithMany()
                        .HasForeignKey("SayimTuruId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.TurSonucuDetay", "TurSonucuDetay")
                        .WithOne("ManuelKarar")
                        .HasForeignKey("StokSayim.Domain.Entities.ManuelKarar", "TurSonucuDetayId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KararVerenKullanici");

                    b.Navigation("SayimTuru");

                    b.Navigation("TurSonucuDetay");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimKaydi", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Ekip", "Ekip")
                        .WithMany()
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimTuru", "SayimTuru")
                        .WithMany("SayimKayitlari")
                        .HasForeignKey("SayimTuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.ApplicationUser", "SayimYapanKullanici")
                        .WithMany()
                        .HasForeignKey("SayimYapanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("SayimTuru");

                    b.Navigation("SayimYapanKullanici");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimKaydiDetay", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimKaydi", "SayimKaydi")
                        .WithMany("Detaylar")
                        .HasForeignKey("SayimKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimKaydi");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimOturumu", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Bolge", "Bolge")
                        .WithOne("SayimOturumu")
                        .HasForeignKey("StokSayim.Domain.Entities.SayimOturumu", "BolgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany()
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimPlanDepoKodu", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimPlani", "SayimPlani")
                        .WithMany("DepoKodlari")
                        .HasForeignKey("SayimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimPlani");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimTuru", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimOturumu", "SayimOturumu")
                        .WithMany("SayimTurlari")
                        .HasForeignKey("SayimOturumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimOturumu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimTuruKatilimci", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.Ekip", "Ekip")
                        .WithMany("SayimTuruKatilimcilari")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokSayim.Domain.Entities.SayimKaydi", "SayimKaydi")
                        .WithMany()
                        .HasForeignKey("SayimKaydiId");

                    b.HasOne("StokSayim.Domain.Entities.SayimTuru", "SayimTuru")
                        .WithMany("Katilimcilar")
                        .HasForeignKey("SayimTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("SayimKaydi");

                    b.Navigation("SayimTuru");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucu", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.SayimTuru", "SayimTuru")
                        .WithOne("TurSonucu")
                        .HasForeignKey("StokSayim.Domain.Entities.TurSonucu", "SayimTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SayimTuru");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucuDetay", b =>
                {
                    b.HasOne("StokSayim.Domain.Entities.TurSonucu", "TurSonucu")
                        .WithMany("Detaylar")
                        .HasForeignKey("TurSonucuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurSonucu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("EkipKullanicilari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Bolge", b =>
                {
                    b.Navigation("EkipGrubu");

                    b.Navigation("SayimOturumu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.Ekip", b =>
                {
                    b.Navigation("EkipGrubuEkipler");

                    b.Navigation("EkipKullanicilari");

                    b.Navigation("SayimTuruKatilimcilari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.EkipGrubu", b =>
                {
                    b.Navigation("Ekipler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolEkip", b =>
                {
                    b.Navigation("Malzemeler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.ErpKontrolOturumu", b =>
                {
                    b.Navigation("Ekipler");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimKaydi", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimOturumu", b =>
                {
                    b.Navigation("GorevBildirimleri");

                    b.Navigation("SayimTurlari");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimPlani", b =>
                {
                    b.Navigation("Bolgeler");

                    b.Navigation("DepoKodlari");

                    b.Navigation("ErpStoklar");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.SayimTuru", b =>
                {
                    b.Navigation("Katilimcilar");

                    b.Navigation("SayimKayitlari");

                    b.Navigation("TurSonucu");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucu", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("StokSayim.Domain.Entities.TurSonucuDetay", b =>
                {
                    b.Navigation("ManuelKarar");
                });
#pragma warning restore 612, 618
        }
    }
}
